export const CREATE_TASK = 'TASK/CREATE_TASK';
export const ENABLE_DISABLE_CHECKBOX = 'TASK/ENABLE_DISABLE_CHECKBOX';
export const DELETE_TASK = 'TASK/DELETE_TASK';
export const START_EDIT_TASK = 'TASK/START_EDIT_TASK';
export const END_EDIT_TASK = 'TASK/END_EDIT_TASK';

